name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt -q install chocolate-doom
    - name: make
      run: make
    - name: run tests
      run: make check
    - name: quickcheck
      run: make -j quickcheck

  windows_crossbuild:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Find Git version
      id: version
      run: |
        export VERSION=$(git rev-parse --short HEAD)
        echo "VERSION=$VERSION-win64" >> $GITHUB_OUTPUT
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt -q install mingw-w64 zip pandoc
    - name: make
      run: make -j8 CC=x86_64-w64-mingw32-gcc
    - name: make package
      run: |
        make windist VERSION=${{steps.version.outputs.VERSION}} \
                     STRIP=x86_64-w64-mingw32-strip
    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        path: "dist"
        name: wadptr-${{steps.version.outputs.VERSION}}
